[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "solutions"
path = "src/solutions.rs"

[dependencies]
nom = "7.1.1"
criterion = "0.4"